before_install:
  - sudo apt-get update

language: python
env:
  - CODECOV_TOKEN='ed8ebcac-7dfe-4635-9044-8e21902aeeaa'
python:
  - "3.10.0"
install:
  - pip install -r requirements.txt
script: python3 -m unittest discover
services: mongodb
