before_install:
  - sudo apt-get update

language: python
env:
  - CODECOV_TOKEN={{secrets.CODECOV_TOKEN}}
python:
  - "3.9"
install:
  - pip install -r requirements.txt
script: python3 -m unittest discover
services: mongodb
